### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by dineshbvadhia** [perone/euclidesdb#13]
Hello. Not an issue but general questions. The doc says "EuclidesDB is a multi-model machine learning feature database". Does this mean a query will be against two or more feature spaces? Secondly, where is the "multi-modal learning" taking place? Thanks

**Comment by perone** [comment]
Hi @dineshbvadhia, you are correct when you say that it means that it will be able to query (and add items) into more than one model (multiple feature spaces), however I didn't understand what do you mean by "multi-modal learning", in the docs we cite "multi-**model**", and there is no learning in EuclidesDB, the model is already pre-trained  when we use it.

**Comment by dineshbvadhia** [comment]
So for example add(vector v1 to feature space#V1, vector v5 to feature space#V5) and query(vector v1unknown, vector v5unknown) are valid statements?

My bad wrt multi-model which I read as multi-modal.

**Comment by perone** [comment]
These are valid statements, however, please note that there is no "add vector", but "add image" for instance. EuclidesDB is responsible for extracting features from the image and not the user application. It is planned to add another RPC service that will accept the addition of items by feature vector, however it wasn't implemented yet and it's not supposed to be the most common use case.

**Comment by dineshbvadhia** [comment]
Ok, thank-you for the clarification.

The docs use the example of similarity search in the fashion industry with multiple trained models for different categories such as shoes, t-shirts, etc. Why not use one pre-trained image model for every category (with transfer learning)? Doesn't trained models for each category increase complexity?

**Comment by leviathan0992** [comment]
@perone I also have a question about EuclidesDB, Its function is stored pre-trained images in order to query by the similar images?

**Comment by perone** [comment]
Hi @Leviathan1995, I don't know if I understood your question, but the idea is to use pre-trained models to extract features and save them into the database, then build an index and query this index with the features from the same model later. Does this answer your question ?

**Comment by leviathan0992** [comment]
@perone Yes, thank you for the explanation, but what is its purpose? Only don't need to be trained again anymore?

**Comment by perone** [comment]
In the docs we have explanation of the purpose and some use cases examples: https://euclidesdb.readthedocs.io/en/latest/.
